-- Requirement 8
-- Customer name and order date

SELECT
    c.customer_name,
    o.order_date
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id;

-- Requirement 9 — JOIN + Revenue

-- This is our first real KPI using joins.

-- Business Goal

-- The finance team wants to know the revenue generated by each order line.
SELECT 
	o.order_id,
   p.product_name,
   oi.quantity,
   (oi.quantity*oi.unit_price) as line_revenue
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
JOIN products p
    ON oi.product_id = p.product_id

-- Requirement 9 — Customer Purchase History

-- This is a genuine interview question.

-- Business Goal

-- The CRM team wants to see everything each customer has purchased.

SELECT
	c.customer_name,
    p.product_name,
    oi.quantity,
    o.order_date
FROM order_items oi
JOIN products p
	ON oi.product_id = p.product_id
JOIN orders o
	ON oi.order_id = o.order_id
JOIN customers c
	ON o.customer_id = c.customer_id;

-- Requirement 10 — Customer Order Analytics

-- Now we combine JOIN + GROUP BY.

-- Business Goal

-- The CEO wants to know how many orders each customer has placed.

SELECT
	c.customer_name,
	count(o.order_id) as total_orders
FROM customers c 
JOIN orders o
	ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.customer_name;

--  Requirement 11 — Product Performance

-- This is the exact query you'd build for a sales dashboard.

-- Business Goal

-- The merchandising team wants to know the total units sold for each product.

SELECT
	p.product_name,
    sum(oi.quantity) as total_units_sold
FROM products p
JOIN order_items oi
	ON p.product_id = oi.product_id
GROUP BY
		p.product_id,
        p.product_name;

-- Final Challenge — Requirement 12 ⭐

-- This combines everything you've learned.

-- Business Goal

-- The CEO wants to know:

-- How many products were purchased by customers in each city?

-- This is a city-level KPI.

SELECT 
	c.city,
    sum(oi.quantity) as total_units_sold
FROM customers c 
JOIN orders o
	ON c.customer_id = o.customer_id
JOIN order_items oi
	ON o.order_id =  oi.order_id
GROUP BY
		c.city;
